"""Add name to drafts

Revision ID: 4eee8789e4ac
Revises: 
Create Date: 2024-07-27 20:10:49.141130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eee8789e4ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
